# Generated by Django 5.0.7 on 2024-11-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_product_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
